version: '3'
services:
  main:
    build: .
    restart: always
    environment:
      PROFILE:
      POSTGRES_PASSWORD:
      BOT_USERNAME:
      BOT_TOKEN:
      BOT_PERMITTED_CHAT_ID:
    ports:
      - ${MAIN_PORT:-0}:8080
  postgres:
    image: postgis/postgis:12-3.1
    restart: always
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
