version: '3'
services:
  main:
    build: .
    restart: always
    environment:
      PROFILE:
      POSTGRES_PASSWORD:
      TELEGRAM_BOT_USERNAME:
      TELEGRAM_BOT_TOKEN:
      TELEGRAM_BOT_PERMITTED_CHAT_ID:
      VK_BOT_TOKEN:
      VK_BOT_PERMITTED_CHAT_ID:
    ports:
      - 127.0.0.1:${MAIN_PORT:-0}:8080
  postgres:
    image: postgis/postgis:12-3.1
    restart: always
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    volumes:
      - postgres:/var/lib/postgresql/data
  minio:
    image: minio/minio:RELEASE.2023-02-22T18-23-45Z.fips
    ports:
      - 127.0.0.1:${MINIO_PORT:-0}:9001
    environment:
      MINIO_ROOT_USER: cocktail_offerer
      MINIO_ROOT_PASSWORD:
    command: server --console-address ":9001" /data
    volumes:
      - minio:/data
volumes:
  postgres:
  minio:
