version: '3'
services:
  main:
    build: .
    restart: always
    environment:
      PROFILE:
      POSTGRES_PASSWORD:
      TELEGRAM_BOT_USERNAME:
      TELEGRAM_BOT_TOKEN:
      TELEGRAM_BOT_PERMITTED_CHAT_ID:
      VK_BOT_TOKEN:
      VK_BOT_PERMITTED_CHAT_ID:
    ports:
      - 127.0.0.1:${MAIN_PORT:-0}:8080
  postgres:
    image: postgis/postgis:12-3.1
    restart: always
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
