spring:
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://postgres:5432/main
    username: postgres
    password: ${POSTGRES_PASSWORD}
cocktail-offerer:
  bot:
    telegram:
      username: ${TELEGRAM_BOT_USERNAME}
      token: ${TELEGRAM_BOT_TOKEN}
      permitted-chat-id: ${TELEGRAM_BOT_PERMITTED_CHAT_ID}
    vk:
      token: ${VK_BOT_TOKEN}
      permitted-chat-id: ${VK_BOT_PERMITTED_CHAT_ID}
