name: core/CD

on:
  push:
    branches: main

jobs:
  cd:
    runs-on: self-hosted
    env:
      PROFILE: prod
      MAIN_PORT: 37142
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      TELEGRAM_BOT_USERNAME: ${{ secrets.TELEGRAM_BOT_USERNAME }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_BOT_PERMITTED_CHAT_ID: ${{ secrets.TELEGRAM_BOT_PERMITTED_CHAT_ID }}
      VK_BOT_TOKEN: ${{ secrets.VK_BOT_TOKEN }}
      VK_BOT_PERMITTED_CHAT_ID: ${{ secrets.VK_BOT_PERMITTED_CHAT_ID }}
    steps:
      - uses: actions/checkout@v2
      - run: ./mvnw install -DskipTests
        working-directory: core
      - run: cp target/*.jar env/
        working-directory: core
      - run: docker-compose -p "cocktail-offerer_$PROFILE" up -d --build
        working-directory: core/env
