name: core/CD

on:
  push:
    branches: main

jobs:
  cd:
    runs-on: self-hosted
    env:
      PROFILE: prod
      MAIN_PORT: 37142
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      BOT_PERMITTED_CHAT_ID: ${{ secrets.BOT_PERMITTED_CHAT_ID }}
    steps:
      - uses: actions/checkout@v2
      - run: ./mvnw install -DskipTests
        working-directory: core
      - run: cp target/*.jar env/
        working-directory: core
      - run: docker-compose -p "cocktail-offerer_$PROFILE" up -d --build
        working-directory: core/env
